server:
  port: 8085

spring:
  application:
    name: pagination
  jackson:
    default-property-inclusion: non_null
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/pagination
    username: pagination
    password: pagination
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
